### ISSUE TITLE
Item variants

### ISSUE THREAD

**Issue by Syr0ws** [Syr0ws/CraftVentory#37]
**User story:** As a configurator, I would like to be able to display a different item at a slot depending on a condition to get my inventory more dynamic.

## Concept

By introducing the concept of **variant**, configurators will be able to change an item view (e.g. the subjacent `ItemStack`) depending on a condition. This concept does not replace the default item, which will always be displayed if no variant is defined or no condition satisfied.

In the configuration, an item will now be defined as follow:
```yaml
close:
    # The ItemStack representation.
    # Here, you can use Bukkit representation or the custom one.
    item:
      type: WHITE_STAINED_GLASS_PANE
    # The symbol used in the pattern to place the item in the inventory.
    # You must ensure that two items do not have the same symbol.
    symbol: "C"
    # The actions executed when a player clicks on the item.
    actions: {}
    # Variants which will be displayed conditionally.
    # This field is optional.
    variants:
      # Variants are defined in sections.
      variant-red:
        # The ItemStack representation.
        # Here, you can use Bukkit representation or the custom one.
        item:
          type: RED_STAINED_GLASS_PANE
        # Predicate to validate to display the variant.
        # If true, the variant will be displayed instead if the condition is true.
        # If no condition can be satisfied, the default item defined in the parent section will be displayed.
        # Conditions are defined using variables that can be targeted using the syntax {variable_name}.
        # Variables must be stored in the inventory model to be available. 
        # For now, only the following types can be manipulated: string, int, double, boolean.
        condition: "{amount} > 0 and {amount} < 35"
      variant-orange:
        item:
          type: ORANGE_STAINED_GLASS_PANE
        condition: "{amount} >= and {amount} < 70"
      variant-green:
        item:
          type: GREEN_STAINED_GLASS_PANE
        condition: "{amount} >= 70"
```
## Actions

In addition to the variant concept, it would be great to also customize item behaviors (e.g. actions) conditionally. Thus, a variant may also have an `actions` property to define its own behavior.

Example:
```yaml
variant-green:
  item:
    type: GREEN_STAINED_GLASS_PANE
  condition: "{amount} >= 70"
  # Actions that will be executed only when the variant is displayed.
  # This property overrides the default actions (e.g. default actions are not executed when the variant is displayed).
  actions: {}
  # This property enables to execute the default item actions.
  # Its goal is to avoid actions duplication by reusing the default ones.
  # The following values are supported:
  # - BEFORE_DEFAULT: Execute variant actions before the default ones.
  # - AFTER_DEFAULT: Execute variant actions after the default ones.
  default-actions: "AFTER_DEFAULT"
```
> This feature implies that it will be necessary to store the currently used item variant to be able to execute the right actions. This can be transparent if the `InventoryItem#getActions()` method returns the item actions depending on the current variant used.
