### ISSUE TITLE
Improve actions configuration

### ISSUE THREAD

**Issue by Syr0ws** [Syr0ws/CraftVentory#70]
Actually, an action is declared by using a section in YAML with at least a `type` property to identify the action. The section name is not really important for the library. Furthermore, we generally don't know what section name to use and it is often repetitive with the action type specified.

For example:
```yaml
actions:
  toggle-activation:
    type: "TOGGLE_WAYPOINT_ACTIVATION"
    click-types:
      - "LEFT"
  open-edit-menu:
    type: "OPEN_WAYPOINT_EDIT_MENU"
    click-types:
      - "RIGHT"
```

This syntax can be improved by using YAML lists of properties. The example above can be then factorized to the following code which is easier to read:

```yaml
actions:
  - type: "TOGGLE_WAYPOINT_ACTIVATION"
    click-types:
      - "LEFT"
  - type: "OPEN_WAYPOINT_EDIT_MENU"
    click-types:
      - "RIGHT"
```

Another change will be to rename the `type` property to `action` which is a more explicit name. Other properties will remain unchanged. The final expected result is the following:

```yaml
actions:
  - action: "TOGGLE_WAYPOINT_ACTIVATION"
    click-types:
      - "LEFT"
  - action: "OPEN_WAYPOINT_EDIT_MENU"
    click-types:
      - "RIGHT"
```
