### ISSUE TITLE
Add reusable item configurations

### ISSUE THREAD

**Issue by Syr0ws** [Syr0ws/CraftVentory#71]
Some items are common between several inventories. For example, the item used to close the inventory can be the same everywhere. Actually, items can only be defined in an inventory configuration file and if we want an item to appear in several inventories in the exact same way, we need to duplicate its definition across several configurations.

We will add a feature that allows to create standalone item configuration files and to reference these items in an inventory configuration. A new `items` folder will be created. Each YAML file in this folder will define a single item configuration.

The configuration will take the following format:
```yaml
id: <value>
item:
  property-1: <value>
  property-2: <value>
  property-3: <value>
```

For example:
```yaml
id: "custom_item"
item:
  name: "&6Item name"
  lore:
    - "line 1"
    - "line 2"
    - "line 3"
```

The item can then be referenced in an inventory configuration file by using the `id` property without defining an `item` property. If an `item` property is present, the local definition will always be taken.
