### ISSUE TITLE
Support several pagination types

### ISSUE THREAD

**Issue by Syr0ws** [Syr0ws/CraftVentory#72]
Actually, only dynamic paginations for which data is provided using Java code can be created. We would like to add two new pagination types: data static and item static.

To differenciate the different pagination types, a new `type` property will be added as a mandatory property when declaring a pagination. This property can takes the following values: `STATIC_DATA`, `STATIC_ITEMS`, `DYNAMIC`.

`STATIC_DATA`: In a static data pagination, instead of being provided dynamically by executing Java code, data is defined statically in a file.

Datasets are defined in files in the `datasets` subfolder. Each dataset is defined in a specific file which can be a YAML or a JSON file. Each dataset is represented with an id (string) and its data (list of objects).

Example in JSON:
```json
{
    "dataset-id": "<value>"
    "data": []
}
```

Example in YAML:
```yaml
dataset-id: "<value>"
data: {}
```

A `STATIC_DATA` pagination must be declared with a `dataset` property associated with the id of the target dataset to use. An exception should be thrown if this property is not present or if the dataset cannot be found.

Example:
```yaml
pagination:
    id: <value>
    type: "STATIC_DATA"
    dataset: <value>
    symbol: <value>
    pagination-item: {}
    previous-page-item: {}
    next-page-item: {}
```

Data can be accessed and displayed with placeholders by using a path syntax. For example, in the following dataset, the `name` property can be displayed by using the placeholder `%data.name%`.

```yaml
dataset-id: "<value>"
data: 
    - name: ""
      value: ""
```

> Note: Only primitives are allowed in data.

`STATIC_ITEM`: In a static item pagination, instead of being provided dynamically, items are defined statically in the inventory configuration file.

The `items` property will be added to the pagination configuration. This property defines a list of items that will be used in the pagination.

Example:
```yaml
pagination:
    id: <value>
    type: "STATIC_ITEM"
    symbol: <value>
    items:
      - name: "<value">
        lore: 
          - "line 1"
          - "line 2"
          - "line 3"
      - name: "<value">
        lore: 
          - "line 1"
          - "line 2"
          - "line 3"
    previous-page-item: {}
    next-page-item: {}
```

> Note: All the item properties can be used. Placeholders can also be used.

`DYNAMIC`: Data are provided dynamically using Java code. 

> Note: This is the current system and the only change will be the adding of the `type` property in the pagination configuration.
